// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJZG-rJXxMpR4AYOXaZv-Ei28DMqRgxnU',
    appId: '1:390806678004:web:9dc1f0b0e5162308cf71a1',
    messagingSenderId: '390806678004',
    projectId: 'naricare-4b1f7',
    authDomain: 'naricare-4b1f7.firebaseapp.com',
    storageBucket: 'naricare-4b1f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC970uXdWqw1UX6aSyrZFHBbiBRsm3NPqQ',
    appId: '1:390806678004:android:89c9ad0998178092cf71a1',
    messagingSenderId: '390806678004',
    projectId: 'naricare-4b1f7',
    storageBucket: 'naricare-4b1f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi6yDTAJgpAOB5coJljzvhQ3nu-HYl1Q0',
    appId: '1:390806678004:ios:e9ac64c1be41e500cf71a1',
    messagingSenderId: '390806678004',
    projectId: 'naricare-4b1f7',
    storageBucket: 'naricare-4b1f7.firebasestorage.app',
    iosBundleId: 'com.example.naricare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi6yDTAJgpAOB5coJljzvhQ3nu-HYl1Q0',
    appId: '1:390806678004:ios:e9ac64c1be41e500cf71a1',
    messagingSenderId: '390806678004',
    projectId: 'naricare-4b1f7',
    storageBucket: 'naricare-4b1f7.firebasestorage.app',
    iosBundleId: 'com.example.naricare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJZG-rJXxMpR4AYOXaZv-Ei28DMqRgxnU',
    appId: '1:390806678004:web:210f1df4daf6f7efcf71a1',
    messagingSenderId: '390806678004',
    projectId: 'naricare-4b1f7',
    authDomain: 'naricare-4b1f7.firebaseapp.com',
    storageBucket: 'naricare-4b1f7.firebasestorage.app',
  );
}
